"""Movies table name to title

Revision ID: 6889227af88a
Revises: d33ba88c6bb0
Create Date: 2024-02-07 22:00:27.452061

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6889227af88a'
down_revision: Union[str, None] = 'd33ba88c6bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_movies_name', table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=True)
    op.drop_column('movies', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index('ix_movies_name', 'movies', ['name'], unique=True)
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###
