"""Movies table added index and unique

Revision ID: d33ba88c6bb0
Revises: ca40f6182530
Create Date: 2024-02-07 21:47:59.732885

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33ba88c6bb0'
down_revision: Union[str, None] = 'ca40f6182530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movies_name'), 'movies', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_name'), table_name='movies')
    # ### end Alembic commands ###
